### ISSUE TITLE
Create Proposal Website for using DashGov.js and submitting real proposals

### ISSUE THREAD

**Issue by coolaj86** [dashhive/ledger#12]
https://github.com/digitalcashdev/DashProposal/

- [x] working proposal submission
- [x] various UX updates from test user feedback
- [x] published publicly (hosting as part of DCD Hosting proposal)

Permanent commits:

- https://github.com/digitalcashdev/DashProposal/commit/89d1a51 feat: DashProposal v1.0.0
- https://github.com/digitalcashdev/DashProposal/commit/f826572 chore: add ./scripts/serve and ./Caddyfile
- https://github.com/digitalcashdev/DashProposal/commit/0595771 doc: add install and deploy instructions
- https://github.com/digitalcashdev/DashProposal/commit/9a6715c doc: add production Caddyfile example
- https://github.com/digitalcashdev/DashProposal/commit/d15d4f0 fix: increase fee, add ability to sweep
- https://github.com/digitalcashdev/DashProposal/commit/ce23e92 ref: show WIF in scan-to-sweep
- https://github.com/digitalcashdev/DashProposal/commit/0727654 ref: clear WIF info and delay before updating
- https://github.com/digitalcashdev/DashProposal/commit/ede879a fix: omit default value for payments
- https://github.com/digitalcashdev/DashProposal/commit/35a200d ref: clearly show scan vs paste as options

**Comment by coolaj86** [comment]
@jojobyte Claiming

Address: Xt9pgpgzo1RE489gTkHzHn9pNnUqjvgx7L

Deliverables here and about 3/4 of the work was recorded live: https://www.youtube.com/watch?v=G9jH-TGwDjc

**Comment by jojobyte** [comment]
@coolaj86 Approved.
