### ISSUE TITLE
Add node and pool tracking and visualization

### ISSUE THREAD

**Issue by coolaj86** [dashhive/ledger#13]
https://github.com/digitalcashdev/DashJoin/

- [x] Can view and track the list of nodes
- [x] Can view and track the CJ pools

Again, many of these commits will be squashed, but I'll put them here for now

- https://github.com/digitalcashdev/DashJoin/commit/afbf315 wip: pool info
- https://github.com/digitalcashdev/DashJoin/commit/1e28027 wip: connection info
- https://github.com/digitalcashdev/DashJoin/commit/fd42096 wip: connection info
- https://github.com/digitalcashdev/DashJoin/commit/0e73c17 f: wip: connection info
- https://github.com/digitalcashdev/DashJoin/commit/394884d f: wip: connection info
- https://github.com/digitalcashdev/DashJoin/commit/4b4f36c fix+ref!: switch connection to working pool

**Comment by coolaj86** [comment]
@jojobyte Claiming

Address: XoaARxWXxTaqdK7vBfAqmgRn1qSUunH7PA

Deliverables: See above.

Also, about 2/3rds of the work for these was captured live: https://www.youtube.com/playlist?list=PLF5Va8rgg4DGvvOhHkzaUgkCkwWZa7zh-

**Comment by jojobyte** [comment]
@coolaj86 Approved.
