### ISSUE TITLE
Add settings for mainnet, wallet paths, and other settings, linting, and UI updates

### ISSUE THREAD

**Issue by coolaj86** [dashhive/ledger#14]
https://github.com/digitalcashdev/DashJoin/

- [x] works on mainnet
- [x] UI to switch network, wallet
- [x] Add Linting + Type Checking
- [x] QR code to fund wallet

Eventually I'll be squashing down a bunch of these commits, but I'll list them here anyway

- https://github.com/digitalcashdev/DashJoin/commit/d313458 chore: add package config and tooling
- https://github.com/digitalcashdev/DashJoin/commit/e4200e2 feat: add tabs, testnet toggle, wallet phrase mask
- https://github.com/digitalcashdev/DashJoin/commit/0e03526 chore: update tooling config
- https://github.com/digitalcashdev/DashJoin/commit/fc04687 feat: add local serve script
- https://github.com/digitalcashdev/DashJoin/commit/b7d639d chore: add qrcode-svg to deps
- https://github.com/digitalcashdev/DashJoin/commit/95f80cc ref: type lint
- https://github.com/digitalcashdev/DashJoin/commit/5723e2d ref!: handle empty wallet and mainnet / testnet switching
- https://github.com/digitalcashdev/DashJoin/commit/7710c4e ref!: show/hide secrets, manage wallet & network settings
- https://github.com/digitalcashdev/DashJoin/commit/8a0a6f2 fix: prevent password manager from showing wallet phrase
- https://github.com/digitalcashdev/DashJoin/commit/20af229 ref: move memo to tools section
- https://github.com/digitalcashdev/DashJoin/commit/b5e854e ref: move address list and export to tools section

**Comment by coolaj86** [comment]
@jojobyte Claiming

Address: Xev9KpNTXAmQhyqqgp3KpKf6HTmHKStFrx

Deliverables: See above.

Also, about 2/3rds of the work for these was captured live: https://www.youtube.com/playlist?list=PLF5Va8rgg4DGvvOhHkzaUgkCkwWZa7zh-

**Comment by jojobyte** [comment]
@coolaj86 Approved.
